# Generated by Django 2.2.6 on 2019-10-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=15)),
                ('phone_no', models.IntegerField(default=None)),
                ('d_o_b', models.DateField(default=None)),
                ('propel_mode', models.CharField(default=None, max_length=15)),
                ('job_state', models.BooleanField(default=True)),
                ('fcc_link', models.CharField(default=None, max_length=150)),
                ('interest', models.CharField(default=None, max_length=250)),
                ('fcc_eligible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('phone_no', models.IntegerField()),
            ],
        ),
    ]
