# Generated by Django 2.2.6 on 2019-10-18 06:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('applicant_id', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('applicant_name', models.CharField(default=None, max_length=15)),
                ('phone_number', models.IntegerField(default=None)),
                ('d_o_b', models.DateField(default=None)),
                ('propel_mode', models.CharField(default=None, max_length=15)),
                ('job_state', models.BooleanField(default=True)),
                ('fcc_link', models.CharField(default=None, max_length=150)),
                ('interest', models.CharField(default=None, max_length=250)),
                ('fcc_eligible', models.BooleanField(default=False)),
                ('approval', models.CharField(choices=[('1', 'Waitlist'), ('2', 'Private'), ('3', 'Not Enough Points'), ('4', 'Wrong Link'), ('5', 'Shortlist'), ('6', 'Joined'), ('7', 'Propel Challenge'), ('8', 'Extended Propel Challenge')], default='1', max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BatchDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_type', models.CharField(max_length=30, null=True)),
                ('date_from', models.DateField(default=datetime.date(2019, 10, 18))),
                ('to_date', models.DateField(default=None)),
                ('strength', models.PositiveIntegerField(default=0)),
                ('mentor_name', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
