# Generated by Django 2.2.6 on 2019-10-19 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchdetail',
            name='date_from',
            field=models.DateField(default=datetime.date(2019, 10, 19)),
        ),
    ]
