# Generated by Django 2.2.6 on 2019-10-16 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='name',
            new_name='applicant_name',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='phone_no',
            new_name='phone_number',
        ),
    ]
