# Generated by Django 2.2.6 on 2019-10-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
