# Generated by Django 2.2.6 on 2019-10-17 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_type', models.CharField(max_length=30, null=True)),
                ('date_from', models.DateField(default=datetime.date(2019, 10, 17))),
                ('to_date', models.DateField(default=None)),
                ('strength', models.IntegerField(default=0)),
                ('mentor_name', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
