# Generated by Django 2.2.6 on 2019-10-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191017_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='approval',
            field=models.CharField(choices=[('1', 'Awaiting'), ('2', 'No'), ('3', 'Yes')], default='1', max_length=1, null=True),
        ),
    ]
