# Generated by Django 2.2.6 on 2019-10-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191019_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='attended_propel_before',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='applicant',
            name='join_confirm',
            field=models.BooleanField(default=None),
        ),
    ]
