# Generated by Django 2.2.6 on 2019-10-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191019_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='points',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
