# Generated by Django 2.2.6 on 2019-10-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_batchdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchdetail',
            name='strength',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
