# Generated by Django 2.2.6 on 2019-10-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_applicant_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='attended_propel_before',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='join_confirm',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
