# Generated by Django 2.2.6 on 2019-10-19 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191019_2030'),
        ('app', '0004_auto_20191019_2041'),
    ]

    operations = [
    ]
