# Generated by Django 2.2.6 on 2019-10-21 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_merge_20191019_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchdetail',
            name='date_from',
            field=models.DateField(default=datetime.date(2019, 10, 21)),
        ),
    ]
