# Generated by Django 2.2.6 on 2019-10-20 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191020_1512'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JoinedCandidates',
            new_name='JoinedCandidate',
        ),
    ]
