# Generated by Django 2.2.6 on 2019-10-20 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191020_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinedcandidate',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='joinedcandidate',
            name='id',
        ),
        migrations.AddField(
            model_name='joinedcandidate',
            name='batch_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.BatchDetail'),
        ),
    ]
