# Generated by Django 2.2.6 on 2019-10-20 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191020_1621'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JoinedCandidate',
        ),
    ]
