# Generated by Django 2.2.6 on 2019-10-20 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_joinedcandidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinedCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=64, null=True)),
                ('joined_on', models.DateField(default=None)),
                ('remarks', models.CharField(max_length=150, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.BatchDetail')),
                ('candidate_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Applicant')),
            ],
        ),
    ]
