# Generated by Django 2.2.6 on 2019-10-20 13:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_joinedcandidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=64, null=True)),
                ('date', models.DateField(default=datetime.date(2019, 10, 20))),
                ('present', models.BooleanField(default=False)),
                ('notes', models.CharField(max_length=250, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.JoinedCandidate')),
            ],
        ),
    ]
