# Generated by Django 2.2.6 on 2019-10-20 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.date(2019, 10, 21)),
        ),
        migrations.AlterField(
            model_name='batchdetail',
            name='date_from',
            field=models.DateField(default=datetime.date(2019, 10, 21)),
        ),
    ]
