# Generated by Django 2.2.6 on 2019-10-20 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20191021_0035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
