# Generated by Django 2.2.6 on 2019-10-20 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_delete_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.IntegerField(default=1, null=True)),
                ('candidate_name', models.CharField(max_length=64, null=True)),
                ('date', models.DateField(default=datetime.date(2019, 10, 21))),
                ('present', models.BooleanField(default=False)),
                ('notes', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
