# Generated by Django 2.2.6 on 2019-10-21 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_merge_20191019_2048'),
        ('app', '0013_attendance'),
    ]

    operations = [
    ]
