# Generated by Django 2.2.6 on 2019-10-21 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191021_1130'),
        ('app', '0013_attendance'),
    ]

    operations = [
    ]
