# Generated by Django 2.2.6 on 2019-10-22 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20191021_1142'),
        ('app', '0015_auto_20191021_1737'),
    ]

    operations = [
    ]
