# Generated by Django 2.2.6 on 2019-10-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_merge_20191021_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='applicant_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='approval',
            field=models.CharField(choices=[('1', 'Waitlist'), ('2', 'Private'), ('3', 'Not Enough Points'), ('4', 'Wrong Link'), ('5', 'Shortlist'), ('6', 'Joined'), ('7', 'Propel Challenge'), ('8', 'Extended Propel Challenge'), ('9', 'Applied')], default='9', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='points',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
