# Generated by Django 2.2.6 on 2019-10-21 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191021_1751'),
        ('app', '0017_auto_20191021_2015'),
    ]

    operations = [
    ]
