# Generated by Django 2.2.6 on 2019-10-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20191022_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskperformance',
            name='task_description',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
