# Generated by Django 2.2.6 on 2019-10-22 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_taskperformance_task_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskperformance',
            old_name='task_id',
            new_name='task',
        ),
    ]
