# Generated by Django 2.2.6 on 2019-10-22 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20191022_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskperformance',
            old_name='joinedcandidates_id',
            new_name='joinedcandidate',
        ),
    ]
