# Generated by Django 2.2.6 on 2019-10-22 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20191022_1234'),
        ('app', '0018_merge_20191021_2027'),
    ]

    operations = [
    ]
