# Generated by Django 2.2.6 on 2019-10-22 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_merge_20191022_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='applicant_name',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='d_o_b',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='fcc_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='fcc_link',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='interest',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='job_state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phone_number',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='propel_mode',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='batchdetail',
            name='date_from',
            field=models.DateField(default=datetime.date(2019, 10, 22)),
        ),
    ]
