# Generated by Django 2.2.6 on 2019-10-22 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_merge_20191022_1351'),
        ('app', '0023_auto_20191022_1558'),
    ]

    operations = [
    ]
